branches:
  only:
  - master
language: node_js
node_js:
  - "12"
services:
  - docker

jobs:
  include:
    - stage: build
      before_script:
        - unset CI
        - npm ci
      script:
        - npm run build
        - docker build -t covidhelp/covidhelp-front:latest -t covidhelp/covidhelp-front:${TRAVIS_COMMIT::8} .
      after_success:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push covidhelp/covidhelp-front
    - stage: deploy
      before_script:
        - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - ssh-keyscan ${APP_DOMAIN} >> ~/.ssh/known_hosts
      script:
        - ssh ${SSH_USER}@${APP_DOMAIN} "export _APP_DOMAIN=${APP_DOMAIN} && export _ACME_EMAIL=${ACME_EMAIL} && echo 1 ${APP_DOMAIN} 2 ${ACME_EMAIL} 3 $_APP_DOMAIN 4 $_ACME_EMAIL"
        - ssh ${SSH_USER}@${APP_DOMAIN} "cd ~/${APP_FOLDER} && git pull && docker-compose pull && APP_DOMAIN=${APP_DOMAIN} ACME_EMAIL=${ACME_EMAIL} docker-compose up -d"