branches:
  only:
  - master
language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
addons:
  ssh_known_hosts: ${APP_DOMAIN}

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

jobs:
  include:
    - stage: build
      before_script:
      - unset CI
      - npm ci
      script:
      - npm run build
      - docker build -t covidhelp/covidhelp-front:latest -t covidhelp/covidhelp-front:${TRAVIS_COMMIT} .
      after_success:
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
      - docker push covidhelp/covidhelp-front
    - stage: deploy
      provider: script
      script:
        - ssh ${SSH_USER}@${APP_DOMAIN} "cd ~/COVID-Help && git pull && docker-compose pull && export APP_DOMAIN=${APP_DOMAIN} && export ACME_EMAIL=${ACME_EMAIL} && docker-compose up -d"