version: "3.7"
services:
  nginx:
    container_name: covidhelp-front
    image: covidhelp/covidhelp-front:latest
    restart: always
    ports:
      - "5000:80"
    networks:
      - front-end
    environment:
      APP_DOMAIN: "${APP_DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=front-end"
      - "traefik.docker.domain=${APP_DOMAIN}"
      - "traefik.frontend.priority=1"
      - "traefik.frontend.rule=Host:${APP_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Proto:https"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

  traefik:
    container_name: traefik
    image: traefik:1.7.16
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    command:
      - "--api"
      - "--logLevel=ERROR"
      - "--traefikLog.format=json"
      - "--accessLog.format=json"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.acmelogging"
      - "--acme.email=${ACME_EMAIL}"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.domains=${APP_DOMAIN}"
      - "--acme.storage=/acme/cert.json"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - front-end
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - acme:/acme
    labels:
      - "traefik.enable=false"

  api-server:
    container_name: covidhelp-api
    restart: always
    image: covidhelp/covidhelp-api:latest
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - front-end
      - back-end
    volumes:
      - ./${STAGE}.env:/usr/src/app/.env

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "covid-help"
    volumes:
      - mongodb:/data/db
    networks:
      - back-end

volumes:
  acme:
  mongodb:
networks:
  front-end:
    name: front-end
  back-end:
    name: back-end
