version: "3.7"
services:
  nginx:
    container_name: covid-help-front
    restart: always
    image: covid-help-front
    ports:
      - "5000:80"
    volumes:
      - ./build:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front-end
    environment:
      APP_DOMAIN: "yourdomain.com" ## EDIT THIS
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=front-end"
      - "traefik.frontend.priority=1"
      - "traefik.frontend.rule=Host:yourdomain.com" ## EDIT THIS
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Proto:https"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

  traefik:
    image: traefik:1.7.16
    container_name: traefik
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    command:
      - "--api"
      - "--logLevel=ERROR"
      - "--traefikLog.format=json"
      - "--accessLog.format=json"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.acmelogging"
      - "--acme.email=yourname@email.com" ## EDIT THIS
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.domains=yourdomain.com" ## EDIT THIS
      - "--acme.storage=/acme/cert.json"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - front-end
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - acme:/acme
    labels:
      - "traefik.enable=false"

volumes:
  acme:

networks:
  front-end:
    name: front-end
  back-end:
    name: back-end
